name: mytorch
channels:
  - gurobi
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - audioread
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - cycler
  - decorator
  - ffmpeg
  - freetype
  - gettext
  - gmp
  - gnutls
  - gurobi
  - jbig
  - joblib
  - jpeg
  - kiwisolver
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libcblas
  - libdeflate
  - libffi
  - libflac
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libiconv
  - liblapack
  - libllvm8
  - libogg
  - libopenblas
  - libopus
  - libpng
  - librosa
  - libsndfile
  - libstdcxx-ng
  - libtiff
  - libvorbis
  - libwebp-base
  - llvmlite
  - lz4-c
  - mad
  - ncurses
  - nettle
  - numba
  - numpy
  - olefile
  - openh264
  - openjpeg
  - openssl
  - pillow
  - pip
  - pycparser
  - pyparsing
  - pysoundfile
  - python=3.7
  - python-dateutil
  - python_abi
  - readline
  - resampy
  - scikit-learn
  - setuptools
  - six
  - sqlite
  - threadpoolctl
  - tk
  - tornado
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - boto3
      - botocore
      - cached-property
      - chardet
      - click
      - filelock
      - gdown
      - h5py
      - idna
      - importlib-metadata
      - jmespath
      - matplotlib
      - pandas
      - protobuf
      - pybind11
      - pyemd
      - python-levenshtein
      - pytz
      - pyyaml
      - regex
      - requests
      - s3transfer
      - sacremoses
      - scipy
      - sentencepiece
      - sox
      - tensorboardx
      - tokenizers
      - torch
      # - torch-baidu-ctc
      - torchvision
      - tqdm
      - transformers
      - typing-extensions
      - urllib3
      - zipp
# prefix: /mnt/home/lichenni/anaconda3/envs/oort
